# Generated by Django 5.0.2 on 2024-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit_date',
            field=models.CharField(max_length=100),
        ),
    ]
