# Generated by Django 5.0.2 on 2024-03-29 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
            preserve_default=False,
        ),
    ]
